//! Parity with `checks.sh`, driven by the frozen fixtures it produced.
//!
//! The three check cases in `fixtures/synthetic/` were generated by running the real harness.
//! Each one's `input/checks.render.tsv` is the check list and its `transcript.txt` records the
//! exit code. A legacy check command is a shell string from trusted project configuration, so
//! it ports to a trusted literal `/bin/sh -c` invocation — what changes is not that shell is
//! forbidden, but that nothing derived from the change under review can be spliced into it.

use std::path::PathBuf;

use review_check::{Arg, CheckDefinition, CheckRunner, CheckStatus, Command, GateDecision};
use review_store::Cas;

fn corpus() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/synthetic")
}

/// Read a case's check list, porting each line to a typed command.
fn definitions(case: &str) -> Vec<CheckDefinition> {
    let tsv = std::fs::read_to_string(corpus().join(case).join("input/checks.render.tsv"))
        .expect("fixture check list");
    tsv.lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with('#'))
        .map(|line| match line.split_once('\t') {
            Some((name, command)) => CheckDefinition::new(
                name,
                Command::new("/bin/sh", vec![Arg::literal("-c"), Arg::literal(command)]),
            ),
            // A malformed line has no command. The harness printed an error, excluded it from
            // its total, and failed the run; here it becomes a check that cannot run, which is
            // strictly more visible and reaches the same verdict.
            None => CheckDefinition::new(line, Command::new("", vec![])),
        })
        .collect()
}

/// The exit code the harness recorded for the `checks.sh` invocation in this case.
fn recorded_exit(case: &str) -> i32 {
    let transcript = std::fs::read_to_string(corpus().join(case).join("transcript.txt")).unwrap();
    transcript
        .lines()
        .find_map(|l| l.strip_prefix("exit="))
        .and_then(|c| c.trim().parse().ok())
        .expect("transcript records an exit code")
}

fn run(case: &str) -> (Vec<review_check::CheckResult>, GateDecision) {
    let dir = tempfile::tempdir().unwrap();
    let cas = Cas::open(dir.path().join("cas")).unwrap();
    let runner = CheckRunner::new(&cas, dir.path());
    let results: Vec<_> = definitions(case).iter().map(|d| runner.run(d)).collect();
    let decision = GateDecision::evaluate(&results);
    (results, decision)
}

#[test]
fn a_vacuous_run_is_not_a_pass() {
    let case = "check-vacuous-run-is-not-a-pass";
    let (results, decision) = run(case);
    assert!(results.is_empty(), "the list is comment-only");
    assert_eq!(decision.exit_code(), recorded_exit(case));
    assert!(decision.reasons[0].contains("vacuous"));
}

#[test]
fn a_failure_is_recorded_and_blocks() {
    let case = "check-failure-is-recorded";
    let (results, decision) = run(case);
    assert_eq!(decision.exit_code(), recorded_exit(case));

    let ok = results.iter().find(|r| r.name == "ok-check").unwrap();
    let bad = results.iter().find(|r| r.name == "bad-check").unwrap();
    assert_eq!(ok.status, CheckStatus::Passed);
    assert_eq!(bad.status, CheckStatus::Failed);
    assert_eq!(bad.exit_code, Some(7), "the real exit code is kept");
    assert!(
        bad.stderr.is_some(),
        "the failing check's output is an artifact, not a path into a directory that gets truncated"
    );
    assert_eq!(decision.blocking, vec!["bad-check"]);
}

#[test]
fn a_check_with_no_command_cannot_run_and_fails_the_gate() {
    let case = "check-with-no-command-fails-the-run";
    let (results, decision) = run(case);
    assert_eq!(decision.exit_code(), recorded_exit(case));

    let malformed = results
        .iter()
        .find(|r| r.name == "no-command-here")
        .unwrap();
    assert_eq!(
        malformed.status,
        CheckStatus::NotRun,
        "a check with no command did not run; it did not fail"
    );
    assert!(malformed.reason.is_some());

    // Deliberate difference from the harness, which excluded the malformed line from its total
    // and printed "1/1 passed" alongside a nonzero exit. Here it is a visible result.
    assert_eq!(decision.executed, 2);
    assert_eq!(decision.required, 2);
    assert_eq!(decision.blocking, vec!["no-command-here"]);
}

/// The property the whole node exists for: two executions of the same check both survive.
#[test]
fn a_later_execution_does_not_erase_an_earlier_one() {
    use review_store::EventStore;

    let dir = tempfile::tempdir().unwrap();
    let cas = Cas::open(dir.path().join("cas")).unwrap();
    let mut store = EventStore::open(dir.path().join("events.sqlite")).unwrap();
    let runner = CheckRunner::new(&cas, dir.path());

    let failing = CheckDefinition::new(
        "build",
        Command::new(
            "/bin/sh",
            vec![
                Arg::literal("-c"),
                Arg::literal("echo first attempt >&2; exit 2"),
            ],
        ),
    );
    let passing = CheckDefinition::new(
        "build",
        Command::new(
            "/bin/sh",
            vec![
                Arg::literal("-c"),
                Arg::literal("echo second attempt; exit 0"),
            ],
        ),
    );

    // The gate runs, fails, someone fixes it, the gate runs again — the shape of round 3 in the
    // frozen load-runner bundle, where the gate ran five times.
    runner
        .run_all(&[failing], &mut store, "run", "gate.attempt-1")
        .unwrap();
    let second = runner
        .run_all(&[passing], &mut store, "run", "gate.attempt-2")
        .unwrap();
    assert!(second[0].passed());

    let events = store.replay("run").unwrap();
    assert_eq!(events.len(), 2, "both executions are in the log");

    let statuses: Vec<String> = events
        .iter()
        .map(|e| e.payload["status"].as_str().unwrap_or_default().to_string())
        .collect();
    assert_eq!(statuses, vec!["failed", "passed"]);

    // The first attempt's output is still readable, which is exactly what `checks.tsv` could
    // not offer: it was truncated at the start of every run.
    let first_stderr = events[0].payload["stderr"].as_str().unwrap();
    assert_eq!(
        String::from_utf8(cas.get(first_stderr).unwrap()).unwrap(),
        "first attempt\n"
    );
    assert_ne!(
        events[0].payload["stderr"], events[1].payload["stderr"],
        "the two attempts are distinct artifacts"
    );
}

/// A record must satisfy the contract, including the shape rule that `not_run` carries a reason
/// and no exit code while an executed check carries the reverse.
#[test]
fn every_result_validates_against_check_result_v1() {
    let schema: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../schemas/check-result-v1.json"),
        )
        .unwrap(),
    )
    .unwrap();
    let validator = jsonschema::validator_for(&schema).unwrap();

    let mut all = Vec::new();
    for case in [
        "check-vacuous-run-is-not-a-pass",
        "check-failure-is-recorded",
        "check-with-no-command-fails-the-run",
    ] {
        all.extend(run(case).0);
    }
    assert!(all.iter().any(|r| r.status == CheckStatus::Passed));
    assert!(all.iter().any(|r| r.status == CheckStatus::Failed));
    assert!(all.iter().any(|r| r.status == CheckStatus::NotRun));

    for result in &all {
        let value = serde_json::to_value(result).unwrap();
        if !validator.is_valid(&value) {
            let errors: Vec<String> = validator
                .iter_errors(&value)
                .map(|e| format!("{} at {}", e, e.instance_path))
                .collect();
            panic!("{} rejected: {}", result.name, errors.join("; "));
        }
        review_store::canonical::canonicalize(&value).expect("a record must be canonicalizable");
    }
}

/// The vector this typing exists to close: a path taken from the diff that looks like an option.
#[test]
fn a_hostile_filename_from_the_diff_cannot_become_an_option() {
    let dir = tempfile::tempdir().unwrap();
    let cas = Cas::open(dir.path().join("cas")).unwrap();
    let runner = CheckRunner::new(&cas, dir.path());

    // `{tests}` filled from the bundle — i.e. from paths in the change under review.
    let check = CheckDefinition::new(
        "stateless-related",
        Command::new(
            "/bin/sh",
            vec![
                Arg::literal("-c"),
                Arg::literal("echo \"$@\""),
                Arg::literal("sh"),
                Arg::untrusted("--config=/tmp/evil"),
            ],
        ),
    );

    let result = runner.run(&check);
    assert_eq!(
        result.status,
        CheckStatus::NotRun,
        "the check must be refused, not run with the value quoted into place"
    );
    assert!(
        result
            .reason
            .as_deref()
            .unwrap()
            .contains("would be read as an option")
    );
    assert!(result.stdout.is_none(), "nothing was executed");
    assert!(!GateDecision::evaluate(&[result]).passed());
}
